include ../../Makefile

test01: CFLAGS += -I../
test01: test01.o ../Graph.o ../GraphSerializer.o

test02: CFLAGS += -I../
test02: test02.o ../Graph.o ../GraphSerializer.o

test03: CFLAGS += -I../
test03: test03.o ../Graph.o ../GraphSerializer.o
